name: Auto Sign
name: Auto Sign

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run auto sign
        env:
          TOKEN: ${{ secrets.TOKEN }}
          EXIT_WHEN_FAIL: ${{ vars.EXIT_WHEN_FAIL }}
          SC3_SENDKEY: ${{ secrets.SC3_SENDKEY }}
          SC3_UID: ${{ secrets.SC3_UID }}
        run: python "天空之境自动签名/main.py"
